<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MovieSeeder extends Seeder
{
    public function run(): void
    {

        $movies = [
            [
                'movieID'      => 1,
                'title'        => 'Phi Vụ Động Trời 2',
                'poster'       => 'https://image.tmdb.org/t/p/original/dAJAUq3WO5w5QUK2YLJTqxTfxio.jpg',
                'background'   => 'https://image.tmdb.org/t/p/original/kPmE7vEwQWSvhQt5P0ZR8NIwNRN.jpg',
                'durationMin'  => 107,
                'rating'       => 'P',
                'genre'        => 'Animation, Action, Comedy, Adventure',
                'releaseDate'  => '2025-11-28',
                'description'  => "“Zootopia 2” đưa khán giả trở lại thành phố động vật náo nhiệt, nơi mọi giống loài cùng chung sống dưới một hệ thống trật tự mong manh. Lần này, sĩ quan Judy Hopps và người đồng hành tinh quái Nick Wilde phải đối mặt với một chuỗi sự kiện bất thường lan rộng khắp thành phố — những dấu hiệu rời rạc nhưng ẩn chứa một âm mưu lớn hơn bất kỳ vụ án nào họ từng đối đầu.\n\nHành trình lần này không chỉ là cuộc chạy đua với thời gian để ngăn chặn thảm họa, mà còn là phép thử của lòng tin, sự can đảm và tình bạn…",
                'is_banner'    => 1,
                'status'       => 'active',
                'created_at'   => '2025-11-30 23:12:11',
                'updated_at'   => '2025-12-02 11:24:59',
            ],
            [
                'movieID'      => 2,
                'title'        => 'Quái Thú Vô Hình: Vùng Đất Chết Chóc',
                'poster'       => 'https://media.themoviedb.org/t/p/w220_and_h330_face/tFoWkywjcmU8wWFJeGHvL9ljAoV.jpg',
                'background'   => 'https://image.tmdb.org/t/p/original/7hDFhV4ng4cHgSnxvO0MIb11Sbp.jpg',
                'durationMin'  => 107,
                'rating'       => 'T13',
                'genre'        => 'Action, Fantasy, Adventure',
                'releaseDate'  => '2025-07-11',
                'description'  => "Quái Thú Vô Hình: Vùng Đất Chết Chóc mở ra một thế giới hoang tàn nơi những sinh vật vô hình thống trị mặt đất bằng tốc độ và sự tàn nhẫn tuyệt đối. Con người buộc phải sống trong im lặng, từng bước đi đều có thể là dấu chấm hết.\n\nKhi một nhóm người sống sót phát hiện tín hiệu cầu cứu từ khu vực được xem là “điểm chết”, họ quyết định liều mạng tiến vào vùng đất bị chia cắt bởi bóng tối, nơi lũ quái thú xuất hiện chỉ trong chớp mắt và không để lại bất kỳ dấu vết nào. Cuộc hành trình đưa họ đối mặt với những bí mật rùng rợn, những thử thách sinh tồn kinh hoàng và sự thật về nguồn gốc của loài quái vật đang xóa sạch nhân loại.\n\nĐó là cuộc chạy đua giữa bản năng sinh tồn và nỗi sợ tuyệt đối – nơi chỉ một âm thanh nhỏ cũng đủ kết liễu tất cả.",
                'is_banner'    => 1,
                'status'       => 'active',
                'created_at'   => '2025-11-30 23:32:56',
                'updated_at'   => '2025-12-02 11:46:39',
            ],
            [
                'movieID'      => 3,
                'title'        => 'Wicked: Phần 2',
                'poster'       => 'https://media.themoviedb.org/t/p/w220_and_h330_face/iFpGz29so4IX8CHAcFZQYk0zsAs.jpg',
                'background'   => 'https://image.tmdb.org/t/p/original/dkNsDcSmArQoKiCAzTbm8gas1JA.jpg',
                'durationMin'  => 137,
                'rating'       => 'P',
                'genre'        => 'Adventure, Fantasy, Romance',
                'releaseDate'  => '2025-11-21',
                'description'  => "Wicked 2 tiếp nối câu chuyện đầy phép thuật và số phận giữa Elphaba – cô phù thủy xanh mang trái tim mạnh mẽ nhưng bị hiểu lầm – và Glinda – phù thủy tốt bụng nhưng giằng xé giữa danh vọng và tình bạn. Khi Thế giới Oz đứng bên bờ hỗn loạn, những bí mật bị che giấu dần lộ diện, kéo hai cô gái vào những lựa chọn có thể thay đổi toàn bộ vận mệnh của họ.\n\nBộ phim mở rộng quy mô của phần đầu với những trường đoạn cảm xúc sâu sắc, hình ảnh huyền ảo và âm nhạc cuốn hút. Wicked 2 không chỉ kể tiếp hành trình của hai phù thủy mà còn khắc họa sự trưởng thành, hi sinh và sức mạnh của tình bạn trong bóng tối và ánh sáng.",
                'is_banner'    => 1,
                'status'       => 'active',
                'created_at'   => '2025-12-01 00:14:30',
                'updated_at'   => '2025-12-02 11:42:51',
            ],
            [
                'movieID'      => 4,
                'title'        => 'Wildcat',
                'poster'       => 'https://media.themoviedb.org/t/p/w220_and_h330_face/h893ImjM6Fsv5DFhKJdlZFZIJno.jpg',
                'background'   => 'https://image.tmdb.org/t/p/original/4kjPMklaHZCklHumSLmJld2GgXW.jpg',
                'durationMin'  => 99,
                'rating'       => 'K',
                'genre'        => 'Action, Adventure',
                'releaseDate'  => '2025-11-25',
                'description'  => "Wildcat theo chân một nữ quân nhân trẻ, cứng rắn nhưng đầy những vết thương tâm lý sau chiến trường, khi cô trở về đời sống thường dân và buộc phải đối mặt với nỗi đau chưa từng được chữa lành. Trong hành trình tìm lại chính mình, cô bị cuốn vào một nhiệm vụ nguy hiểm không chính thức, nơi ranh giới giữa đúng và sai ngày càng mờ nhạt.\n\nGiữa bạo lực, cô độc và những bí mật quân sự bị chôn vùi, Wildcat khai thác sâu nội tâm của một chiến binh bị tổn thương, đặt người xem vào cuộc đấu tranh giữa bản năng sinh tồn và khao khát được sống như một con người bình thường. Bộ phim mang sắc thái u tối, căng thẳng và đầy thời khắc bùng nổ, dẫn dắt khán giả đi qua cả sự khốc liệt lẫn vẻ đẹp mong manh của con người khi đối diện quá khứ.",
                'is_banner'    => 1,
                'status'       => 'active',
                'created_at'   => '2025-12-01 01:32:57',
                'updated_at'   => '2025-12-02 11:41:35',
            ],
            [
                'movieID'      => 5,
                'title'        => 'Cục 749',
                'poster'       => 'https://media.themoviedb.org/t/p/w220_and_h330_face/flykCMw22y6yv8vKnBjmsW3pneo.jpg',
                'background'   => 'https://image.tmdb.org/t/p/original/lf8IZ86ajGpgbuyHCZrXUeAMmvy.jpg',
                'durationMin'  => 82,
                'rating'       => 'T16',
                'genre'        => 'Action, Thriller, Adventure, Sci-Fi',
                'releaseDate'  => '2024-01-10',
                'description'  => "Trong Border Hunters, một đội đặc nhiệm biên giới tinh nhuệ phải đối mặt với những đường dây tội phạm xuyên quốc gia ngày càng tàn bạo và tinh vi. Khi một chiến dịch truy quét tưởng chừng đơn giản biến thành cuộc chiến sinh tử, họ buộc phải lần theo dấu vết của một tổ chức ngầm sở hữu mạng lưới trải rộng khắp biên giới.\n\nGiữa những khu rừng hiểm trở, sa mạc khắc nghiệt và các vùng giáp ranh không luật pháp, đội đặc nhiệm phải đối mặt với những kẻ buôn lậu liều lĩnh, những tay săn người máu lạnh và cả bóng tối trong chính bản thân mình. Border Hunters là hành trình nghẹt thở, nơi lòng trung thành và ý chí sinh tồn bị thử thách đến giới hạn cuối cùng.",
                'is_banner'    => 1,
                'status'       => 'active',
                'created_at'   => '2025-12-01 01:36:26',
                'updated_at'   => '2025-12-02 11:44:27',
            ],
            [
                'movieID'      => 6,
                'title'        => 'Chú Thuật Hồi Chiến: -Biến Cố Shibuya x Tử Diệt Hồi Du',
                'poster'       => 'https://media.themoviedb.org/t/p/w220_and_h330_face/sBffPvE9Kau726nnU14cTOEj3Pq.jpg',
                'background'   => 'https://image.tmdb.org/t/p/original/gtKglOSEq3d4MgQE4VsrT1sRkd0.jpg',
                'durationMin'  => 88,
                'rating'       => 'T13',
                'genre'        => 'Action, Animation',
                'releaseDate'  => '2025-12-05',
                'description'  => "“Biến Cố Shibuya x Tử Diệt Hồi Du” đưa người xem vào giai đoạn hỗn loạn nhất của thế giới chú thuật, nơi ranh giới giữa sự sống – cái chết bị xoá nhoà bởi những âm mưu đen tối. Shibuya chìm trong phong ấn, hàng ngàn thường dân bị nhốt giữa chiến trường của các chú thuật sư và nguyền hồn cấp đặc biệt. Gojo Satoru đối đầu liên minh nguyền hồn trong một trận chiến mang tính định mệnh, trong khi Itadori, Megumi và Nobara buộc phải bước vào điểm sôi của bi kịch.\n\nSong song đó, Tử Diệt Hồi Du đưa khán giả trở lại quá khứ của Fushiguro Toji cùng những sự kiện dẫn đến bi kịch gia tộc Zenin — mở ra mảnh ghép quan trọng cho bí mật ẩn sâu của thế giới chú thuật.\n\nBộ phim là sự kết hợp giữa hành động tốc độ cao, cảm xúc nặng nề và những khoảnh khắc bùng nổ, khiến khán giả nghẹt thở từ đầu đến cuối. Đây là chương tối tăm nhất, đau đớn nhất và cũng mãn nhãn nhất trong hành trình của Jujutsu Kaisen.",
                'is_banner'    => 1,
                'status'       => 'active',
                'created_at'   => '2025-12-01 01:39:34',
                'updated_at'   => '2025-12-02 11:41:19',
            ],

            [
                'movieID'      => 7,
                'title'        => 'Avatar: Lửa và Tro Tàn',
                'poster'       => 'https://media.themoviedb.org/t/p/w220_and_h330_face/w6DBmG260sCHBQdGzkBIVn9gAQZ.jpg',
                'background'   => 'https://image.tmdb.org/t/p/original/6hLkMunNnFzZTkKxHDHdbI7bPw4.jpg',
                'durationMin'  => 192,
                'rating'       => 'T13',
                'genre'        => 'Action, Adventure, Fantasy',
                'releaseDate'  => '2025-12-19',
                'description'  => "Sau cuộc chiến tàn khốc với RDA và nỗi mất mát to lớn khi đứa con trai cả hy sinh, Jake Sully và Neytiri phải đối mặt với một mối đe dọa mới trên Pandora: tộc Tro Tàn — một nhóm Na'vi hung bạo và khát khao quyền lực, do thủ lĩnh tàn nhẫn Varang dẫn dắt. Gia đình Jake buộc phải chiến đấu để sinh tồn và bảo vệ tương lai của Pandora, trong một cuộc xung đột đẩy họ đến giới hạn cuối cùng cả về thể xác lẫn tinh thần.",
                'is_banner'    => 1,
                'status'       => 'active',
                'created_at'   => '2025-12-02 11:12:29',
                'updated_at'   => '2025-12-02 11:40:01',
            ],

            [
                'movieID'      => 8,
                'title'        => 'Năm Đêm Kinh Hoàng 2',
                'poster'       => 'https://media.themoviedb.org/t/p/w220_and_h330_face/iv7ktbyc5OP5ksQ6ccRjwvk8LAJ.jpg',
                'background'   => 'https://image.tmdb.org/t/p/original/vTxxMQk6ZOUSvcjBYIPjXRpInul.jpg',
                'durationMin'  => 104,
                'rating'       => 'T13',
                'genre'        => 'Fantasy, Thriller',
                'releaseDate'  => '2025-12-05',
                'description'  => "Sau những sự kiện kinh hoàng tại Freddy Fazbear’s Pizza, bí mật đen tối tưởng chừng đã bị chôn vùi. Nhưng khi một trung tâm giải trí mới được xây dựng trên nền tàn tích cũ, những con animatronic “được nâng cấp” lại bắt đầu hành xử bất thường, phát ra những âm thanh kỳ lạ và xuất hiện ở những nơi chúng không thuộc về.\n\nMột nhân viên bảo vệ ca đêm mới nhận việc — và anh ta nhanh chóng nhận ra rằng điều đang truy đuổi mình không chỉ là máy móc. Ánh mắt vô hồn, tiếng bước chân rền rĩ trong hành lang tối và những bóng hình di chuyển trong camera đã báo hiệu một cơn ác mộng lặp lại.\n\nKhi các manh mối về quá khứ đẫm máu của Freddy và những đứa trẻ mất tích dần hé lộ, anh buộc phải đối mặt với sự thật rằng nơi đây chưa bao giờ “được làm lại”, mà chỉ bị che đậy bằng những nụ cười giả tạo.\n\nMột lần nữa, năm đêm trở thành địa ngục — và lần này, không phải ai cũng sống sót để kể lại.",
                'is_banner'    => 1,
                'status'       => 'active',
                'created_at'   => '2025-12-02 11:30:14',
                'updated_at'   => '2025-12-02 11:40:28',
            ],

            [
                'movieID'      => 9,
                'title'        => 'Hàng Xóm Của Tôi Là Totoro',
                'poster'       => 'https://media.themoviedb.org/t/p/w220_and_h330_face/cogogd1s0xSafd9PE6dtwEry4Oz.jpg',
                'background'   => 'https://image.tmdb.org/t/p/original/eB7TCPGsoc8liVR3SmAxeBYRUgn.jpg',
                'durationMin'  => 86,
                'rating'       => 'P',
                'genre'        => 'Animation, Adventure',
                'releaseDate'  => '2025-12-19',
                'description'  => "Khi hai chị em Satsuki và Mei chuyển về vùng nông thôn yên bình để gần bệnh viện nơi mẹ họ điều trị, một thế giới kỳ diệu đã âm thầm mở ra giữa khu rừng phía sau ngôi nhà. Trong những cánh đồng gió thổi hiu hiu và những góc rừng phủ đầy rêu xanh, Mei tình cờ gặp Totoro — sinh vật to lớn, bí ẩn nhưng hiền lành, chỉ có thể nhìn thấy bởi những trái tim thuần khiết.\n\nSatsuki ban đầu không tin, nhưng rồi cô cũng chạm mặt Totoro vào một đêm mưa, nơi chiếc ô bé nhỏ đã kết nối cả hai thế giới. Từ đó, các em bước vào những chuyến phiêu lưu nhiệm màu: bay trên chiếc “quay chong”, gọi mèo-bus huyền thoại, và khám phá những điều kỳ diệu ẩn dưới vẻ bình yên của làng quê Nhật Bản.\n\nTotoro không chỉ là một người bạn tưởng tượng — mà còn là biểu tượng của tuổi thơ, của niềm tin rằng phép màu luôn tồn tại, chỉ cần ta lắng nghe nhịp thở của thiên nhiên và trái tim mình.",
                'is_banner'    => 1,
                'status'       => 'active',
                'created_at'   => '2025-12-02 11:31:14',
                'updated_at'   => '2025-12-02 11:53:12',
            ],

            [
                'movieID'      => 10,
                'title'        => 'Mai',
                'poster'       => 'https://media.themoviedb.org/t/p/w220_and_h330_face/n764Alj5Uf1uMtnEpN3OkVyLob5.jpg',
                'background'   => 'https://image.tmdb.org/t/p/original/zZ6nRdNQNxRnZ1LQ2ttPBZl9AXV.jpg',
                'durationMin'  => 131,
                'rating'       => 'T13',
                'genre'        => 'Drama, Romance',
                'releaseDate'  => '2024-10-02',
                'description'  => "“Mai” xoay quanh cuộc đời một cô gái trẻ bị cuốn vào bi kịch sau một sự kiện đen tối trong quá khứ. Cố gắng thoát khỏi bóng đêm đó để tìm lại chính mình, Mai phải đối mặt với những tổn thương, dằn vặt và sự phán xét từ xã hội. Bộ phim là hành trình chữa lành đầy cảm xúc, khắc họa lòng mạnh mẽ của một cô gái không chịu khuất phục trước số phận.",
                'is_banner'    => 1,
                'status'       => 'active',
                'created_at'   => '2025-12-02 11:33:00',
                'updated_at'   => '2025-12-02 11:38:01',
            ],

            [
                'movieID'      => 11,
                'title'        => 'Tử chiến trên không',
                'poster'       => 'https://media.themoviedb.org/t/p/w220_and_h330_face/elhC01GA3etoh6X9zj5QwZq20Js.jpg',
                'background'   => 'https://image.tmdb.org/t/p/original/3oQcPT8lPVL0vAK56Fj4KFLuEfn.jpg',
                'durationMin'  => 108,
                'rating'       => 'T16',
                'genre'        => 'Action, Thriller',
                'releaseDate'  => '2025-09-19',
                'description'  => "“Tử Chiến Trên Không” kể về một phi đội chiến đấu tinh nhuệ được điều động tham gia nhiệm vụ ngăn chặn một mối đe dọa quân sự bất ngờ. Khi không chiến bùng nổ dữ dội trên bầu trời, mỗi phi công không chỉ chiến đấu vì nhiệm vụ mà còn vì những điều họ muốn bảo vệ. Những màn đối đầu nghẹt thở, chiến thuật căng não và tinh thần đồng đội tạo nên một trận chiến sinh tử không khoan nhượng.",
                'is_banner'    => 1,
                'status'       => 'active',
                'created_at'   => '2025-12-02 11:34:08',
                'updated_at'   => '2025-12-02 11:38:41',
            ],

            [
                'movieID'      => 12,
                'title'        => 'Mưa đỏ',
                'poster'       => 'https://image.tmdb.org/t/p/original/iM0fWP6rPeRSfQ2hOEGVb3NP2Qh.jpg',
                'background'   => 'https://image.tmdb.org/t/p/original/kH5atmGEdHcg73xZa8J4UJ2V2Ax.jpg',
                'durationMin'  => 124,
                'rating'       => 'T13',
                'genre'        => 'Drama, War',
                'releaseDate'  => '2025-08-22',
                'description'  => "Trong một thị trấn nhỏ vốn yên bình, những trận “mưa đỏ” kỳ bí bất ngờ xuất hiện, kéo theo hàng loạt hiện tượng kinh hoàng và các vụ biến mất bí ẩn. Một nhóm người sống sót buộc phải tìm hiểu sự thật trước khi thảm họa bao trùm toàn bộ khu vực. Càng đào sâu, họ càng phát hiện những bí mật đen tối bị chôn vùi từ nhiều năm trước. “Mưa Đỏ” mang màu sắc kinh dị–sinh tồn, kết hợp không khí huyền bí và cảm giác căng thẳng đến nghẹt thở.",
                'is_banner'    => 1,
                'status'       => 'active',
                'created_at'   => '2025-12-02 11:36:22',
                'updated_at'   => '2025-12-02 11:37:19',
            ],

        ];
        DB::table('movies')->upsert(
            $movies,
            ['movieID'], 
            [
                'title',
                'poster',
                'background',
                'durationMin',
                'rating',
                'genre',
                'releaseDate',
                'description',
                'is_banner',
                'status',
                'created_at',
                'updated_at',
            ]
        );
    }
}
